# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitPair < Formula
  desc "A simple CLI app to make it easier for pairing for co-authoring commits"
  homepage "https://github.com/inverse/git-pair/"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/inverse/git-pair/releases/download/v0.1.7/git-pair_Darwin_arm64.tar.gz"
      sha256 "2978aefc0d3d9a6a8b47430b92c34e2851ad89e5030da27ed7c03fef4d387615"

      def install
        bin.install "git-pair"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/inverse/git-pair/releases/download/v0.1.7/git-pair_Darwin_x86_64.tar.gz"
      sha256 "c9294f059b2f8c72824a32edac17381b7e868b83ccf5bc272a11ed0f8c226770"

      def install
        bin.install "git-pair"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/inverse/git-pair/releases/download/v0.1.7/git-pair_Linux_x86_64.tar.gz"
      sha256 "43e6c1976756553fbf07f0fbb19ff22c172116632d3969ef05be9d0a9433a532"

      def install
        bin.install "git-pair"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inverse/git-pair/releases/download/v0.1.7/git-pair_Linux_arm64.tar.gz"
      sha256 "ed5eb7b34fdd0809ac5a7f5b875c0ba0c8576f521940368055de3451b59c9004"

      def install
        bin.install "git-pair"
      end
    end
  end

  test do
    system "#{bin}/git-pair --version"
  end
end
