# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitPair < Formula
  desc "A simple CLI app to make it easier for pairing for co-authoring commits"
  homepage "https://github.com/inverse/git-pair/"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inverse/git-pair/releases/download/v0.1.8/git-pair_Darwin_x86_64.tar.gz"
      sha256 "4dff25bedbabb7441efa4dfcaca51cea078b4eee0dff8eb4257b083a598127b6"

      def install
        bin.install "git-pair"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inverse/git-pair/releases/download/v0.1.8/git-pair_Darwin_arm64.tar.gz"
      sha256 "58a92a816217965280b73f846acc81f304e4eb14134211d99c52da9a4e215eac"

      def install
        bin.install "git-pair"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/inverse/git-pair/releases/download/v0.1.8/git-pair_Linux_x86_64.tar.gz"
      sha256 "d2f82d1319bb7436e65a41158964d1b5212b64530af38f74ebe36c30bb40f1df"

      def install
        bin.install "git-pair"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inverse/git-pair/releases/download/v0.1.8/git-pair_Linux_arm64.tar.gz"
      sha256 "47c85594a5d696dfe023b9611cecaaf0d7c50cf0e7ba028a72c5de2dc9796b20"

      def install
        bin.install "git-pair"
      end
    end
  end

  test do
    system "#{bin}/git-pair --version"
  end
end
